# Generated by Django 2.0.6 on 2018-06-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180628_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='link',
        ),
    ]
